# Generated by Django 2.2 on 2019-05-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20190512_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='sitestatus',
            field=models.CharField(choices=[('NEW', 'New Site'), ('EX', 'Existing Site')], max_length=20),
        ),
    ]
